### ISSUE TITLE
Custumize Objective-funtion

### ISSUE THREAD

**Issue by Lydia-bka** [jules-leguy/EvoMol#3]
Is it possible to implement an Objective function according to a self-defined parameter that is not in the set of Implemented functions already available in Evomol?

**Comment by jules-leguy** [comment]
It is possible to give any python function evaluating a SMILES as an objective function of EvoMol.

For instance, the following fragment of code will maximize the number of carbon atoms in the molecule. Note that the custom function is given here with its name as a tuple but could be also given directly as a value of the "obj_function" entry.

```python
from rdkit.Chem import Lipinski, MolFromSmiles
from evomol import run_model

def count_carbon_atoms(smiles):
    return Lipinski.HeavyAtomCount(MolFromSmiles(smiles)) - Lipinski.NumHeteroatoms(MolFromSmiles(smiles))  

run_model({
    "obj_function": (count_carbon_atoms, "custom_count_carbons")
})

```

**Comment by Lydia-bka** [comment]
Thank you for your support.
Lydia
